In [ ]:
# Ch11-2-using-sgkit

In [ ]:
# Install libraries
! pip install sgkit
! pip install 'sgkit[plink]'

In [1]:
# 10.  Load dataset from previous recipe
import numpy as np 
from sgkit.io import plink 
data = plink.read_plink(path='hapmap10_auto_noofs_ld', fam_sep='\t') 

In [2]:
# 11.  Check the structure of the data
data 

<xarray.Dataset>
Dimensions:             (contigs: 22, variants: 54944, alleles: 2,
                         samples: 1198, ploidy: 2)
Dimensions without coordinates: contigs, variants, alleles, samples, ploidy
Data variables: (12/14)
    contig_id           (contigs) <U2 '1' '2' '3' '4' ... '19' '20' '21' '22'
    variant_contig      (variants) int16 0 0 0 0 0 0 0 ... 21 21 21 21 21 21 21
    variant_position    (variants) int32 dask.array<chunksize=(54944,), meta=np.ndarray>
    variant_allele      (variants, alleles) |S1 dask.array<chunksize=(54944, 1), meta=np.ndarray>
    sample_id           (samples) <U7 dask.array<chunksize=(1198,), meta=np.ndarray>
    call_genotype       (variants, samples, ploidy) int8 dask.array<chunksize=(54944, 1198, 2), meta=np.ndarray>
    ...                  ...
    sample_family_id    (samples) <U7 dask.array<chunksize=(1198,), meta=np.ndarray>
    sample_member_id    (samples) <U7 dask.array<chunksize=(1198,), meta=np.ndarray>
    sample_paternal_id  (samples) <U1 dask.array<chunksize=(1198,), meta=np.ndarray>
    sample_maternal_id  (samples) <U1 dask.array<chunksize=(1198,), meta=np.ndarray>
    sample_sex          (samples) int8 dask.array<chunksize=(1198,), meta=np.ndarray>
    sample_phenotype    (samples) int8 dask.array<chunksize=(1198,), meta=np.ndarray>
Attributes:
    contigs:  ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',...
    source:   sgkit-0.9.0

In [3]:
# 12.  Get summary information
print(data.dims) 

Frozen({'contigs': 22, 'variants': 54944, 'alleles': 2, 'samples': 1198, 'ploidy': 2})


In [4]:
# 13.  Extract information about samples
print(len(data.sample_id.values)) 
print(data.sample_id.values) 
print(data.sample_family_id.values) 
print(data.sample_sex.values) 

1198
['NA19916' 'NA19835' 'NA20282' ... 'NA18915' 'NA19250' 'NA19124']
['2431' '2424' '2469' ... 'Y029' 'Y113' 'Y076']
[1 2 2 ... 1 2 1]


In [5]:
# 14.  Review contigs
print(data.contigs) 

<xarray.DataArray 'contigs' (contigs: 22)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])
Dimensions without coordinates: contigs


In [6]:
# 15. Look at the variants
print(len(data.variant_contig.values)) 
print(data.variant_contig.values) 
print(data.variant_position.values) 
print(data.variant_allele.values) 
print(data.variant_id.values) 

54944
[ 0  0  0 ... 21 21 21]
[  742584   782343   843817 ... 49440955 49498590 49528105]
[[b'A' b'G']
 [b'C' b'T']
 [b'A' b'C']
 ...
 [b'T' b'C']
 [b'C' b'T']
 [b'A' b'C']]
['rs3131972' 'rs2905036' 'rs1806509' ... 'rs11912064' 'rs6010061'
 'rs11705587']


In [7]:
# 16.  Look at Genotype data
call_genotype = data.call_genotype.values 
print(call_genotype.shape) 
first_individual = call_genotype[:,0,:] 
first_variant = call_genotype[0,:,:] 
first_variant_of_first_individual = call_genotype[0,0,:] 
print(first_variant_of_first_individual) 
print(data.sample_family_id.values[0], data.sample_id.values[0]) 
print(data.variant_allele.values[0]) 

(54944, 1198, 2)
[0 0]
2431 NA19916
[b'A' b'G']


In [ ]:
## End of Notebook ##